### ISSUE TITLE
shmem test fails on Fedora 37

### ISSUE THREAD

**Issue by boxerab** [saprykin/plibsys#100]
```
25/28 Test #18: pshmbuffer_test ..................***Failed    5.01 sec
Running test case: pshmbuffer_nomem_test
Running test case: pshmbuffer_bad_input_test
Running test case: pshmbuffer_general_test
/home//src/plibsys/tests/pshmbuffer_test.cpp:286: check failed
Running test case: pshmbuffer_thread_test
Test failed
```

**Comment by boxerab** [comment]
This test fails:

`P_TEST_CHECK (p_shm_buffer_get_free_space (buffer, NULL) == (10 - sizeof (test_str_sm)));`

**Comment by saprykin** [comment]
I tested it with latest Fedora 38 (AArch64), works fine with both GCC and Clang compilers. Please, re-open of the issue is still there or you have special runtime conditions to investigate.
