### ISSUE TITLE
Unable create share memory more than 4GB on windows

### ISSUE THREAD

**Issue by leekunpeng** [saprykin/plibsys#106]
Hi~ When i use plibsys in my program, i foud it can't create a share memory which size is more than 4GB on windows.  In the “pshm-win.c”, line 74. function CreateFileMappingA(), argument dwMaximumSizeHigh was set to 0. And that cause this problem. 
Could you fix this?
Thanks.
Best.

**Comment by saprykin** [comment]
Thanks for the PR! I have a few questions to clarify:

- Maybe we should not have a test for 4GB. My concern is what would happen on Windows XP with less than 4 GB? Some embedded machines may also have less than 4GB of physical memory available. There is a clear problem with Windows API usage (what PR is fixing), but I would prefer to avoid having extreme test cases which potentially cannot be run on low-performance machines.
- In LOWDWORD macro, why do you need to do shifts at all? I guess you can just cut high word like this: `#define LODWORD(l) ((DWORD)((DWORDLONG)(l)))`

**Comment by leekunpeng** [comment]
Sorry for the delay.

I agree with you, 4GB is really not needed for testing on a windows XP machine.  I added this just to test, i suggest you can remove it.
But now i am using plibsys to develop cross-platform applications. Our program have a need to mem allocate 4GB of shared memory on windows.  So i summit a PR.  I have change LOWDWORD macro and delete 4GB mem test.

Can you please help to solve this problem? 
Thanks a lot!
