### ISSUE TITLE
Are there any plans to release a new version soon?

### ISSUE THREAD

**Issue by MonicaLiu0311** [saprykin/plibsys#110]
I am the maintainer of vcpkg. The last version of plibsys 0.0.4 was released in 2018. I found that you have always had commit records. Do you have any plans to release a new version in the near future?

**Comment by MonicaLiu0311** [comment]
I see that you have the intention to export the `plibsys-config.cmake` and `plibsys-targets.cmake` files. 
https://github.com/saprykin/plibsys/blob/master/src/CMakeLists.txt#L936
```
install (TARGETS ${PLIBSYS_INSTALL_TARGETS} EXPORT plibsys-targets ...)
```

Are you willing to complete the code and provide these files? For example:
https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L429-L446
https://github.com/fmtlib/fmt/blob/master/support/cmake/fmt-config.cmake.in

**Comment by saprykin** [comment]
@MonicaLiu0311 A new release 0.0.5 is out, let me know if you experience any issues with that.
