### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by saprykin** [saprykin/plibsys#71]
It seems that the LGPL 2.x-3.x license is not the best way to distribute software that could be used in commercial purposes, especially for development of applications for Apple's AppStore. It is still possible to somehow use LGPL licence for developers, but it doesn't make their life better. We need either to add a static linkage exception to the license (which means it would be a new license derived from LGPL, basically it something similar to what Mozilla did with MPL), or to switch to another license.

MIT license looks like a good candidate for that.

**Comment by solvingj** [comment]
If you had some reason for using LGPL and you wish to offer the option, you can do dual-licensing.  Here are some projects which do this today:

https://libcxx.llvm.org/ 
https://github.com/actor-framework/actor-framework
https://github.com/log4cplus/log4cplus#license

**Comment by saprykin** [comment]
Switched to MIT license.
