### ISSUE TITLE
Run binaries on QNX target

### ISSUE THREAD

**Issue by abhaynayak24** [saprykin/plibsys#73]
I'm able to execute the simple hello world code on momentics IDE on windows host with QNX OS running on VMware. However, is there a way to run the binaries directly on QNX?

**Comment by saprykin** [comment]
What do you mean by run directly? You can always use SSH or FTP to transfer binaries, login to QNX and run the binaries on QNX without Momentics.

**Comment by abhaynayak24** [comment]
Thanks, but I'm not able to find the executables on my host (windows). Where are these binaries stored?

**Comment by saprykin** [comment]
I don't remember exactly where Momentics stores them, but somewhere in the build folder of the project. Look in the settings.

**Comment by abhaynayak24** [comment]
Thanks @saprykin 
Just one more things, I tried sending the files using SSH but SSH doesn't work on QNX, I tried the password "root" but it says its incorrect. The graphics-startup.sh also fails to run, can't see the UI. Probably the image has some issue. Can you suggest anything?

**Comment by saprykin** [comment]
You need to configure SSH server on QNX. In order to be able to login as root remotely via SSH, you need to enable PermitRootLogin in the SSH server config.
