### ISSUE TITLE
Unclear build instructions

### ISSUE THREAD

**Issue by Milinai** [saprykin/plibsys#77]
Hello, I am very new to GitHub and C++, but I know some basics of them both. I would like the building instructions to be more clear and include information such as where to put the files when cloning or if that can be done anywhere, and I haven't found how to use the library. This is what I would like to know after knowing what this library can do. Any help is appreciated.

**Comment by saprykin** [comment]
@Milinai,
Did you check the wiki pages for building instructions: https://github.com/saprykin/plibsys/wiki/Building-library ? I think it should be clear from this page how to build the library. Maybe I should add to Readme a link on the wiki.

What is unclear for you about the library usage? I mean, if you have a CMake project - it is pretty straightforward to include this library into your existing project. If you have any other build system - again, the same way you go with any other C/C++ library: specify for a compiler where the headers are, specify for a linker where the binary objects are.

Thanks for the feedback!

**Comment by Milinai** [comment]
I'm pretty sure I did that, I looked again. What I would like to know is if there is some special path or drive to clone the repo to when building. What's next is: what should I `#include` in my project and is there a documentation? If yes, I didn't find it.

**Comment by saprykin** [comment]
@Milinai,
There is no special places where you should clone it. You just clone the source code of the library wherever you want, then you create an empty build directory (again, wherever you want), and then you go to the build directory (`cd` command) and execute `cmake` to configure the project for specific compilers and IDEs. For example, in the command `cmake -DCMAKE_BUILD_TYPE=Release ../plibsys` the last argument points to the cloned directory with sources.

Regarding the documentation on library usage it still requires some improvement. You need only to include `plibsys.h` header. You can see examples on how to use it in the `test` folder where each test is basically a program that uses the library. Documentation generated by Doxygen is also available here: https://saprykin.github.io/plibsys-docs/

Anyway, I hope to improve the documentation on library usage in upcoming days.

**Comment by Milinai** [comment]
Thank you! I would like the information in the first paragraph to be found easily, and I missed the documentation link in the readme.
