### ISSUE TITLE
bug in pp_shm_buffer_get_free_space function

### ISSUE THREAD

**Issue by lgpseu** [saprykin/plibsys#88]
https://github.com/saprykin/plibsys/blob/1631fe68f048f81f749645aae3e56d9d0c544a0a/src/pshmbuffer.c#L58
To distinguish the buffer is full or empty when write_pos equals read_pos, one byte space is reversed, so the free space should
  be read_pos - write_pos - 1 when write_pos < read_pos.

**Comment by saprykin** [comment]
Hi @lgpseu,
Thanks for finding it, should be now fixed in ec6be3fb05516b6d6e8a414c28ad0147ddd9c258.
